server:
  host: "0.0.0.0"
  port: 8080

security_rules:
  - rule_name: "SQL Injection Protection"
    description: "Block SQL Injection attempts"
    action: "block"
  - rule_name: "XSS Protection"
    description: "Block Cross-Site Scripting (XSS)"
    action: "block"

rate_limiting:
  enabled: true
  max_requests_per_minute: 100

tls:
  enabled: true
  certificate: "/path/to/certificate.pem"
  private_key: "/path/to/private_key.pem"
